@startuml
User -> ContextFactory: buildContext()
ContextFactory -> ContextXmlReader: getValues()
ContextXmlReader -> ContextFactory: return object of context.xml records

ContextFactory -> WebXmlReader: getValues()
WebXmlReader -> LdapResolver: resolve()
LdapResolver -> WebXmlReader: return resource value from ldap
WebXmlReader -> ContextFactory: return object of web.xml records

ContextFactory -> ContextFactory: putEnv()
@enduml
