@startuml
User -> ContextSuport: buildContext()
ContextSuport -> ContextXmlReader: getValues()
ContextXmlReader -> ContextSuport: return object of context.xml records

ContextSuport -> WebXmlReader: getValues()
WebXmlReader -> ContextSuport: return object of web.xml records

ContextSuport -> ContextSuport: putEnv()
@enduml
